[package]
name = "opossum_gui"
version = "0.7.0-2"
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = true
readme = "README.md"

[dependencies]
opossum_backend = { workspace = true }

approx.workspace = true
chrono.workspace = true
itertools.workspace = true
log.workspace = true
nalgebra.workspace = true
num.workspace = true
ron.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
tempfile.workspace = true
tokio.workspace = true
uom.workspace = true
uuid.workspace = true

dioxus = { version = "0.6"}
dioxus-free-icons = { version = "0.9", features = ["font-awesome-solid"] }
directories = "6.0.0"
futures-util = "0.3.31"
ico = "0.4"
Inflector = "0.11.4"
reqwest = { version = "0.12.14", features = ["json", "stream"] }
rfd = "0.15.3"
rust-sugiyama = "0.3"

# wasm-bindgen = "0.2"
# wasm-bindgen-futures = "0.4.50"
# serde-wasm-bindgen = "0.6.5"

[build-dependencies]
winres = "0.1"

# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# plotly = { version = "0.13.5", features = ["kaleido"] }
# [target.'cfg(target_arch = "wasm32")'.dependencies]
# plotly = { version = "0.13.5" }

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = ["dioxus/server"]

[lib]
crate-type = ["cdylib", "rlib"]
