[package]
name = "opossum_gui"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = true
readme = "README.md"

[dependencies]
opossum_core = { workspace = true }

approx.workspace = true
chrono.workspace = true
itertools.workspace = true
log.workspace = true
nalgebra.workspace = true
num.workspace = true
ron.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
tempfile.workspace = true
uom.workspace = true
uuid.workspace = true

dioxus = { version = "0.7" }
dioxus-free-icons = { version = "0.10", features = ["font-awesome-solid"] }
directories = "6"
futures-util = "0.3"
ico = "0.5"
Inflector = "0.11"
reqwest = { version = "0.13", features = ["json", "stream"] }
rfd = { version = "0.17" }
rust-sugiyama = "0.4"
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }
regex = "1"
webbrowser = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["process", "time"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1", default-features = false }
web-sys = "0.3"

[build-dependencies]
winres = "0.1"

# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# plotly = { version = "0.13.5", features = ["kaleido"] }
# [target.'cfg(target_arch = "wasm32")'.dependencies]
# plotly = { version = "0.13.5" }

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
# server = ["dioxus/server"]
