[application]
name = "opossum_gui"
icon = "assets/favicon.ico" # Controls window & EXE resource directly

[web.app]
title = "OPOSSUM"

[bundle]
identifier = "com.opossumlabs.opossum"
publisher = "OpossumLabs"
short_description = "Open-source optic simulation system and unified modeler"
long_description = "An open-source framework for the simulation of optical (laser) systems based on directed network graphs"
category = "Utility"
icon = [
    "assets/icons/32x32.png",
    "assets/icons/64x64.png",
    "assets/icons/128x128.png",
    "assets/icons/256x256.png",
    "assets/icons/512x512.png"
]

# Example files generated dynamically into the workspace target directory
resources = [
    "../target/opm_examples/workshop_00_kepler_paraxial.opm",
    "../target/opm_examples/workshop_01_kepler_real_lenses.opm",
    "../target/opm_examples/workshop_02_kepler_chromatism.opm",
    "../target/opm_examples/workshop_03_kepler_wavefront.opm",
    "../target/opm_examples/workshop_04_kepler_imaging_point.opm",
    "../target/opm_examples/workshop_06_geometry_mirrors.opm",
    "../target/opm_examples/workshop_07_geometry_shifted_lens.opm",
    "../target/opm_examples/workshop_08_reference_node.opm",
    "../target/opm_examples/workshop_09_phelix.opm",
    "../target/opm_examples/workshop_10_multi_path.opm",
    "../target/opm_examples/workshop_11_ghostfocus.opm"
]

# Sidecar binaries staged inside the workspace target directory (Workaround for Dioxus bundling)
external_bin = [
    "../target/staging/opossum_backend",
    "../target/staging/opossum_cli",
    "../target/staging/opossum_backend.exe",
    "../target/staging/opossum_cli.exe"
]

[bundle.windows]
icon_path = "assets/favicon.ico"
timestamp_url = "http://timestamp.digicert.com"
tsp = true
allow_downgrades = true

[bundle.windows.webview_install_mode.EmbedBootstrapper]
silent = false

[bundle.windows.wix]
skip_webview_install = true
enable_elevated_update_task = false
fips_compliant = false
banner_path = "../opossum_core/logo/Logo_InstallBanner.png"
dialog_image_path = "../opossum_core/logo/Logo_InstallDialog.png"
license_path = "../LICENSE"