[application]
name = "opossum_gui"
icon = "assets/favicon.ico" # Steuert Fenster & EXE-Ressource direkt

[web.app]
title = "OPOSSUM"

[bundle]
identifier = "com.opossumlabs.opossum"
publisher = "OpossumLabs"
short_description = "Open-source optic simulation system and unified modeler"
long_description = "An open-source framework for the simulation of optical (laser) systems based on directed network graphs"
category = "Utility"
icon = ["assets/Logo_square.png"]
# resources = ["./opm_examples"]

# Workaround for Dioxus bundling bug
external_bin = [
    "staging/opossum_backend",
    "staging/opossum_cli",
    "staging/opossum_backend.exe",
    "staging/opossum_cli.exe"
]

[bundle.windows]
icon_path = "assets/favicon.ico"
timestamp_url = "http://timestamp.digicert.com"
tsp = true
allow_downgrades = true

[bundle.windows.webview_install_mode.EmbedBootstrapper]
silent = false

[bundle.windows.wix]
skip_webview_install = true
enable_elevated_update_task = false
fips_compliant = false
banner_path = "../opossum_core/logo/Logo_InstallBanner.png"
dialog_image_path = "../opossum_core/logo/Logo_InstallDialog.png"
license_path = "../LICENSE"