[application]
icon = "assets/favicon.ico"
name = "opossum_gui"

[web.app]
title = "OPOSSUM"

[web.resource.dev]
script = []

[bundle]
identifier = "com.opossumlabs.opossum"
publisher = "OpossumLabs"
short_description = "Open-source optic simulation system and unified modeler"
long_description = "An open-source framework for the simulation of optical (laser) systems based on directed network graphs"
category = "Utility"
icon = ["assets/Logo_square.png"]
# this is only for windows. It seems to be ignored for linux...
resources = ["../target/release/opossum_backend.exe","../target/release/opossum_core.exe"]

[bundle.windows]
icon_path = "assets/favicon.ico"
timestamp_url = "http://timestamp.digicert.com"
tsp = true
allow_downgrades = true
resources = ["../target/release/opossum_backend.exe","../target/release/opossum_core.exe"]

[bundle.windows.webview_install_mode.EmbedBootstrapper]
silent = false

[bundle.windows.wix]
language = []
fragment_paths = []
component_group_refs = []
component_refs = []
feature_group_refs = []
feature_refs = []
merge_refs= []
skip_webview_install = true
enable_elevated_update_task= false
fips_compliant = false
banner_path = "../opossum_core/logo/Logo_InstallBanner.png"
dialog_image_path = "../opossum_core/logo/Logo_InstallDialog.png"
license_path = "../LICENSE"

[bundle.deb]
# bundle the helper binaries
files = { "usr/lib/OpossumGui/opossum_backend" = "../target/release/opossum_backend", "usr/lib/OpossumGui/opossum_core" = "../target/release/opossum_core"}
