[package]
name = "opm_macros_lib"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "opm_macros_lib"
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "*"
syn = { version = "*", features = ["full", "extra-traits"] }
