[package]
name = "opm_macros_lib"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "opm_macros_lib"
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }
proc-macro2 = "1"

[dev-dependencies]
trybuild = "1.0"
opossum_core = { workspace=true }
