[package]
name = "opossum_cli"
version = "0.7.0-beta.1"
edition = "2024"
authors = [
  "Udo Eisenbarth <u.eisenbarth@gsi.de>",
  "Yannik Zobus <y.zobus@gsi.de>",
]
description = "Open-source Optics Simulation Software and Unified Modeler"
repository = "https://github.com/opossum-labs/opossum"
license = "GPL-3.0"
keywords = ["laser", "optics", "physics", "simulation"]
categories = ["science", "simulation"]
publish = true
# build = "build.rs"
readme = "../README.md"

[dependencies]
opossum_core = { path = "../opossum_core" }
clap = { version = "4", features = ["derive", "string"] } # command line argument parser
log = "0.4"
env_logger= "0.11"
rprompt = "2"