# default:
  # Official language image. Look for the different tagged releases at:
  # https://hub.docker.com/r/library/rust/tags/
  # image: "rust:latest"

before_script:
   # avoid /n -> /r/n conversion on windows
   - git config --global core.autocrlf false
   #  - apt-get update -yqq
   #  - apt-get install -yqq --no-install-recommends build-essential

stages:
  - test
  - build

# test_windows:
#   stage: test
#   tags:
#     - windows
#   script:
#     # - rustup default nightly
#     # - cargo install junitify
#     # junitify does not find some files under windows ???
#     - cargo test # -- --format=json -Z unstable-options --report-time | junitify --out $CI_PROJECT_DIR\tests\
#   rules:
#   - if: '$CI_COMMIT_REF_PROTECTED == "true"'
# #  artifacts:
# #    when: always
# #    reports:
# #      junit: $CI_PROJECT_DIR/tests/*.xml

test_windows:
  stage: test
  tags:
    - windows
  script:
    - cargo-clippy --version
    - rustc --version
    - cargo xtask ci
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'

# Build the main application
build-windows:
  stage: build
  tags:
    - windows
  script:
    - cargo dist build
  dependencies:
    - test_windows
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
  artifacts:
    untracked: false
    when: on_success
    paths: 
      - distrib/*.msi
      - distrib/*.zip
      - distrib/*.tar.gz

# Build the main application for linux
#build-linux:
#  stage: build
#  tags:
#    - linux
#  script:
#    - cargo build --release
#  dependencies:
#    - test:cargo

# Build API documentation
build-doc:
  stage: build
  tags:
    - windows
  script:
    - cargo doc --no-deps --features doc-images
  dependencies:
    - test_windows
  rules:
  - if: '$CI_COMMIT_REF_PROTECTED == "true"'
