[package]
name = "opossum"
version = "0.3.0"
edition = "2021"
authors = [
  "Udo Eisenbarth <u.eisenbarth@gsi.de>",
  "Yannik Zobus <y.zobus@gsi.de>",
]
description = "Open-source Optics Simulation Software and Unified Modeler"
repository = "https://git.gsi.de/phelix/rust/opossum/"
license = "GPL-3.0-or-later"
keywords = ["laser", "optics", "physics", "simulation"]
categories = ["science", "simulation"]
publish = false
build = "build.rs"

[dependencies]
petgraph = { version = "0", features = ["serde-1"] } # the graph library
uom = {version="0", features = ["serde"] }
serde = { version = "1" }
serde_derive = "1"
serde_yaml = "0"
serde_json = "1"

# for spectrum
# ndarray = { version = "0", features = ["serde"] }
# ndarray-stats = "0"
csv = "1"
plotters = "0"

approx = "0" # assert macros for comparison of floats with tolerance
clap = { version = "4", features = ["derive", "string"] } # command line argument parser
rprompt = "2.0"
strum = { version = "0", features = ["derive"] }

uuid = { version = "1", features = ["v4", "fast-rng", "serde"] }

chrono = { version= "0", features = ["serde"] }

embed-doc-image = "0" # allows for embedded images in the rust API doc

itertools-num="0"
ncollide2d = "0.33"
nalgebra = { version= "0", features = ["serde-serialize"] }

genpdf={ version="0", features = ["images"] }
image="0.23"
tempfile="3"
rand="0"
sobol="1"
[features]
doc-images = []

[build-dependencies]
# All features enabled
vergen = { version = "8", features = [
  "git",
  "gitcl",
] } # get git version infos compiled in binary
