[package]
name = "opossum"
version = "0.1.0"
edition = "2021"
authors = ["Udo Eisenbarth <u.eisenbarth@gsi.de>", "Yannik Zobus <y.zobus@gsi.de>"]
description = "Open-source optics simulation software and unified modeller"
repository = "https://git.gsi.de/phelix/rust/opossum/"
license = "GPL-2.0-or-later"
keywords = ["laser", "optics", "physics", "simulation"]
categories = [ "science", "simulation"]
publish = false

[dependencies]
