[package]
name = "opossum"
version = "0.1.0"
edition = "2021"
authors = ["Udo Eisenbarth <u.eisenbarth@gsi.de>", "Yannik Zobus <y.zobus@gsi.de>"]
description = "Open-source optics simulation software and unified modeller"
repository = "https://git.gsi.de/phelix/rust/opossum/"
license = "GPL-2.0-or-later"
keywords = ["laser", "optics", "physics", "simulation"]
categories = [ "science", "simulation"]
publish = false

[dependencies]
petgraph = {version="0.6.3", features = ["serde-1"]} # the graph library
uom = "0"
serde = "1"
serde_derive = "1"
serde_yaml = "0"

# for spectrum
ndarray= { version="0", features= ["serde"]}
ndarray-stats="0"
csv="1"
plotters="0"
