[workspace]
members = ["opossum_core", "opossum_backend", "opossum_gui", "xtask", "opossum_cli"]
default-members = ["opossum_core", "opossum_backend", "opossum_gui"]
resolver = "3"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
strip = true

[profile.release]
# Optimize for size. "z" is even smaller than "s".
# opt-level = "z"
# Link-Time Optimization increases compile time but reduces binary size.
lto = true
# Reduces parallelism in the compiler, allowing for better optimization.
codegen-units = 1
# Abort on panic rather than unwinding the stack.
panic = "abort"
# Automatically strip symbols from the binary.
strip = true 

# Disable debug symbols an link time optimization due to limitations of the Linux pipeline VM.
[profile.test]
debug = 0
lto = "off"

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
