[Setup]
; Basic application metadata
AppName=OPOSSUM
AppVersion=0.1.0
; Unique identifier for the application (generated via Tools -> Generate GUID in Inno Setup)
AppId=A3F4B5C6-D7E8-4F90-A1B2-C3D4E5F6A7B8
AppPublisher=OpossumLabs
DefaultDirName={autopf}\OPOSSUM
DefaultGroupName=OPOSSUM
SetupIconFile=opossum_gui\assets\favicon.ico
Compression=lzma2/max
SolidCompression=yes
; Force native 64-bit mode (installs to C:\Program Files and uses 64-bit Registry)
ArchitecturesInstallIn64BitMode=x64compatible
; Output configuration
OutputDir=target\release
OutputBaseFilename=opossum_installer_x64

; Link the icon for Windows "Apps & Features" / "Add-Remove Programs"
UninstallDisplayIcon={app}\opossum_gui.exe

; Automatically detect and close running instances of OPOSSUM before installing/updating
CloseApplications=yes
RestartApplications=yes

[Files]
; Core executables from the cargo release build
Source: "target\dx\opossum_gui\release\windows\app\opossum_gui.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "target\release\opossum_backend.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "target\release\opossum_cli.exe"; DestDir: "{app}"; Flags: ignoreversion
; Include assets
Source: "target\dx\opossum_gui\release\windows\app\assets\*"; DestDir: "{app}\assets"; Flags: ignoreversion recursesubdirs
; Include workshop examples generated by xtask
Source: "target\opm_examples\*"; DestDir: "{app}\opm_examples"; Flags: ignoreversion recursesubdirs

[Icons]
; Clean shortcuts inside the Windows Start Menu and Desktop with correct icons
Name: "{group}\OPOSSUM"; Filename: "{app}\opossum_gui.exe"; IconFilename: "{app}\opossum_gui.exe"
; Name: "{autodesktop}\OPOSSUM"; Filename: "{app}\opossum_gui.exe"; IconFilename: "{app}\opossum_gui.exe"

; [Run]
; Option to launch the application right after installation
; Filename: "{app}\opossum_gui.exe"; Description: "{cm:LaunchProgram,OPOSSUM}"; Flags: nowait postinstall skipifsilent
