//! GhostFocus Analysis Example
//!
//! This example demonstrates how to construct a simple optical system and
//! configure a GhostFocus analysis using a collimated laser source.
//!
//! System Overview
//! 1. One collimated optical source
//! 2. Three mirrors
//! 3. Two transmissive lenses with configurable optical coatings
//! 4. A GhostFocus analyzer configured for multiple reflection events
//! 5. Serialization of the complete optical system for later visualization
//!    and analysis
//!
//! Principles and Objectives
//! Ghost reflections are unintended optical paths produced by partial
//! reflections at optical surfaces such as lenses or windows. These
//! secondary beams can propagate through the optical system, creating
//! stray light, image artifacts, or localized intensity hotspots.
//!
//! This example demonstrates how to build an optical system suitable for
//! GhostFocus analysis by assigning optical properties to each
//! component and defining a physical laser source.
//!
//! The simulated beam is defined by:
//! - a hexagonally sampled collimated beam,
//! - a two-dimensional Gaussian energy distribution
//! - and a monochromatic laser spectrum.
//!
//! The GhostFocus analyzer evaluates ghost paths generated by surface
//! reflections. The maximum number of allowed
//! reflection events (bounces) can be configured to control how many ghost
//! paths are evaluated.
//!
//! This example demonstrates:
//! - How to build an optical system using mirrors and lenses
//! - How to connect optical components with physical propagation distances
//! - How to assign optical coatings and laser-induced damage thresholds (LIDT)
//! - How to define a physically realistic collimated laser source
//! - How to configure a GhostFocus analyzer for stray-light analysis
//! - How to save the complete optical system as an `.opm` document
//!
//! Imports:
//! - `opossum_core::prelude::*` provides optical components, analyzers,
//!   unit macros, and document types
//! - `opossum_core::coatings::*` provides optical coating models
//! - `opossum_core::distributions::*` provides beam position, energy,
//!   and spectral distributions
//! - `std::{env, path::Path}` is used to determine the output directory and
//!   save the generated `.opm` file.

use opossum_core::coatings::CoatingConstantR;
use opossum_core::{
    J_per_cm2, coatings::CoatingType, distributions::energy::General2DGaussian,
    distributions::position::HexagonalTiling, distributions::spectral::LaserLines,
};
use opossum_core::{percent, prelude::*};
use std::env;
use std::path::Path;
/// Entry point of the GhostFocus simulation.
///
/// Returns:
/// - `OpmResult<()>` indicating successful execution
///   or an optical-system error.
fn main() -> OpmResult<()> {
    // Create the top-level optical system container.
    // A NodeGroup stores all optical components and their interconnections.
    let mut scenery = NodeGroup::new("Ghostfocus demo");
    // Create the optical source.
    // The physical beam properties are assigned later through the
    // GhostFocus analyzer configuration.
    let mut src = SourcePort::new("collimated ray source");
    // Assign the laser-induced damage threshold (LIDT) of the source output.
    src.set_lidt(&PortType::Output, "output_1", J_per_cm2!(2.0))?;
    // Add the source to the optical system.
    let i_src = scenery.add_node(src)?;
    // First steering mirror redirecting the beam by 45°.
    let mir1 = scenery.add_node(ThinMirror::new("Mirror 1").with_tilt(degree!(45., 0., 0.))?)?;

    // First lens with constant-reflectivity coatings on both surfaces.
    // The coating introduces ghost reflections that can later be analyzed.
    let mut lens = Lens::default();
    lens.node_attr_mut().set_name("Lens 1");
    lens.set_coating(
        &PortType::Input,
        "input_1",
        &CoatingConstantR::new(percent!(5.0))?.into(),
    )?;
    lens.set_coating(
        &PortType::Output,
        "output_1",
        &CoatingConstantR::new(percent!(5.0))?.into(),
    )?;
    // Assign LIDT values for both optical surfaces.
    lens.set_lidt(&PortType::Input, "input_1", J_per_cm2!(2.0))?;
    lens.set_lidt(&PortType::Output, "output_1", J_per_cm2!(2.0))?;
    let i_l = scenery.add_node(lens)?;

    // Second steering mirror redirecting the beam toward the second lens
    let mir2 = scenery.add_node(ThinMirror::new("Mirror 2").with_tilt(degree!(45., 0., 0.))?)?;

    // Second lens.
    //
    // The constant-reflectivity coating shown below is overwritten by the
    // subsequent Fresnel coating assignment. Consequently, the simulation
    // uses Fresnel reflections for both surfaces.
    let mut lens2 = Lens::default();
    lens2.node_attr_mut().set_name("Lens 2");
    lens2.set_coating(
        &PortType::Input,
        "input_1",
        &CoatingConstantR::new(percent!(20.0))?.into(),
    )?;
    lens2.set_coating(
        &PortType::Output,
        "output_1",
        &CoatingConstantR::new(percent!(20.0))?.into(),
    )?;
    lens2.set_coating(&PortType::Input, "input_1", &CoatingType::Fresnel)?;
    lens2.set_coating(&PortType::Output, "output_1", &CoatingType::Fresnel)?;
    lens2.set_lidt(&PortType::Input, "input_1", J_per_cm2!(2.0))?;
    lens2.set_lidt(&PortType::Output, "output_1", J_per_cm2!(2.0))?;
    let i_l2 = scenery.add_node(lens2)?;

    // Final mirror directing the beam to the system output.
    let mir3 = scenery.add_node(ThinMirror::new("Mirror 3"))?; // .with_tilt(degree!(5., 0., 0.))?)?;

    // Connect all optical components.
    // Each connection specifies the free-space propagation distance between
    // adjacent components.
    scenery.connect_nodes(i_src, "output_1", mir1, "input_1", millimeter!(50.0))?;
    scenery.connect_nodes(mir1, "output_1", i_l, "input_1", millimeter!(125.0))?;
    scenery.connect_nodes(i_l, "output_1", mir2, "input_1", millimeter!(65.0))?;
    scenery.connect_nodes(mir2, "output_1", i_l2, "input_1", millimeter!(100.0))?;
    scenery.connect_nodes(i_l2, "output_1", mir3, "input_1", millimeter!(150.0))?;

    let mut doc = OpmDocument::new(scenery);

    // Define the physical laser source used by the GhostFocus analyzer.
    //
    // The beam consists of:
    // - hexagonal spatial sampling,
    // - a Gaussian energy profile,
    // - and a monochromatic spectrum at 1000 nm.
    let ray_data_source = RayDataSource::Collimated(CollimatedSrc::new(
        HexagonalTiling::new(millimeter!(15.0), 25)?.into(),
        General2DGaussian::new(
            joule!(2.),
            millimeter!(0., 0.),
            millimeter!(8., 8.),
            5.,
            radian!(0.),
            false,
        )?
        .into(),
        LaserLines::new(vec![(nanometer!(1000.0), 1.0)])?.into(),
    ));
    // Configure the GhostFocus analyzer.
    let mut config = GhostFocusConfig::default();
    // Associate the optical source with the defined beam model.
    config.map_source(i_src, ray_data_source.into());
    // Allow ghost rays to undergo up to two reflection events.
    config.set_max_bounces(2);
    // Attach the analyzer to the simulation document.
    doc.add_analyzer(AnalyzerType::GhostFocus(config));

    // Read the output directory from the environment, fallback to playground.
    let out_dir = env::var("OPOSSUM_EXAMPLES_OUT_DIR")
        .unwrap_or_else(|_| "./opossum_core/playground".to_string());
    let out_path = Path::new(&out_dir).join("workshop_11_ghostfocus.opm");

    // Save the complete optical system.
    // The generated file can later be opened in the OPOSSUM framework for
    // visualization and GhostFocus analysis.
    doc.save_to_file(&out_path)
}
