//! ![OPOSSUM logo][opossum_logo]
//!
//! This is the documentation for the **OPOSSUM** software package. **OPOSSUM** stands for
//! **Op**en-source **O**ptics **S**imulation **S**oftware and **U**nified **M**odeler.
//!
#![cfg_attr(feature = "doc-images",
cfg_attr(all(),
doc = ::embed_doc_image::embed_image!("opossum_logo", "logo/Logo_text.svg")))]
#![cfg_attr(
    not(feature = "doc-images"),
    doc = "**Doc images not enabled**. Compile with feature `doc-images` and Rust version >= 1.54 \
           to enable."
)]
#![allow(clippy::module_name_repetitions)]
pub mod absorption;
pub mod analyzers;
pub mod apertures;
pub mod coatings;
pub mod core_optics;
pub mod distributions;
pub mod error;
pub mod generic_validators;
mod kde;
pub mod light;
pub mod nodes;
pub mod opm_document;
pub mod prelude;
pub mod properties;
pub mod refractive_index;
pub mod types;
// pub mod render;
pub mod asset;
pub mod geometry;
pub mod material;
pub mod reporting;
pub mod utils;

pub use material::{material_air, material_vaccuum};

use chrono::DateTime;

// Allows internal macro expansions that use the ::opossum_core:: path
// to resolve correctly within this crate itself.
extern crate self as opossum_core;
/// Return the version information of the currently built OPOSSUM executable.
///
/// This function returns a `String` which contains the current Git tag/hash combination as well as
/// the timestamp of this commit. If compiled outside a Git repository (e.g., during mutant testing),
/// it falls back to default placeholders.
#[must_use]
pub fn get_version() -> String {
    // Attempt to read the commit timestamp generated by vergen
    let timestamp = option_env!("VERGEN_GIT_COMMIT_TIMESTAMP").map_or_else(
        || String::from("unknown date"),
        |ts_str| {
            DateTime::parse_from_rfc3339(ts_str).map_or_else(
                |_| String::from("invalid timestamp"),
                |dt| dt.format("%Y/%m/%d %H:%M").to_string(),
            )
        },
    );

    // Attempt to read the git describe string, default to "unknown version"
    let describe = option_env!("VERGEN_GIT_DESCRIBE").unwrap_or("unknown version");
    format!("{describe} ({timestamp})")
}
#[cfg(test)]
mod test {
    use crate::error::{OpmResult, OpossumError};

    use super::*;
    use regex::Regex;
    #[test]
    #[ignore]
    fn get_ver() -> OpmResult<()> {
        let version_string = get_version();
        let re = Regex::new(r"(.*) \(\d{4}/\d{2}/\d{2} \d{2}:\d{2}\)")
            .map_err(|e| OpossumError::Other(format!("Error in regular expression: {e}")))?;
        assert!(re.is_match(&version_string));
        Ok(())
    }
}
