[package]
name = "opossum_core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = true
build = "build.rs"
readme = "README.md"

[package.metadata.wix]
upgrade-guid = "6A79F3B1-0417-472C-8C99-F1ADB17DE27D"
path-guid = "56710F06-5772-4D76-BA9F-83122E49A2C3"
license = false
eula = false
timestamp = "Versign"
product-icon = "opossum/logo/Logo_square.ico"
banner = "opossum/logo/Logo_InstallBanner.png"
dialog = "opossum/logo/Logo_InstallDialog.png"

# [lib]
# crate-type = ["cdylib", "rlib"] # Necessary for WASM build

[dependencies]
opm_macros_lib = { workspace = true }
approx.workspace = true
chrono.workspace = true
itertools.workspace = true
log.workspace = true
nalgebra.workspace = true
ron.workspace = true
serde.workspace = true
strum.workspace = true
strum_macros.workspace = true
tempfile.workspace = true
uom.workspace = true
utoipa.workspace = true
uuid.workspace = true

petgraph = { version = "0.8", features = ["serde-1"] } # the graph library
plotters = "0.3"
libm = { version = "0.2" }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
fastrand = "2.3"
sobol = "1"
colorous = "1"
delaunator = "1"
kahan = "0.1"
roots = "0.0.8"
voronator = "0.2"
rayon = "1"
tinytemplate = "1"
spade = "2"
earcutr = "0.5"
num-traits = "0.2"
mutants = "0.0.4"
inventory = "0.3"
indexmap = { version = "2", features = ["serde"] }

[features]
doc-images = []

[dev-dependencies]
static_assertions = "1.1"
regex = "1"
assert_matches = "1"
testing_logger = "0.1"
criterion = { version = "0.8.0", features = ["html_reports"] }

[build-dependencies]
vergen-gix = { version = "10.0" } # get git version infos compiled in binary

[[example]]
name = "hhts"
path = "examples/hhts/hhts.rs"

[[example]]
name = "grating_examples"
path = "examples/grating_examples/grating_examples.rs"

[[bench]]
name = "fluence_estimator"
harness = false

[[bench]]
name = "ray_bench"
harness = false

[[bench]]
name = "surface_benches"
harness = false
