[book]
authors = ["Udo Eisenbarth <u.eisenbarth@gsi.de>", "Yannik Zobus <y.zobus@gsi.de>"]
language = "en"
multilingual = false
src = "src"
title = "OPOSSUM Handbook"


[preprocessor.katex]
after = ["links"]
