# profile = "codegen"

[env]
OPM_FILE_VERSION = "0"
RUST_TEST_THREADS = "1"

[alias]
xtask = "run --package xtask --"

[build]
jobs=8

[rust]
debug--assertions = true

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

