[package]
name = "opossum_registry"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
opossum_core = { path = "../opossum_core" }
ron.workspace = true
serde.workspace = true
tempfile.workspace = true
uom.workspace = true
uuid.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
gix = { version = "0.87.1", features = [
    "blocking-http-transport-reqwest",
    "worktree-mutation",
    "revision"
] }